### ISSUE TITLE
grp not found

### ISSUE THREAD

**Issue by onaclov2000** [jroose/shtk#25]
ModuleNotFoundError: No module named 'grp'

I ran into this issue when running on windows. I'm not familiar with the grp package, but possibly this is something that should be referenced in setup.py?

**Comment by jroose** [comment]
Right now the project is Linux-only.  The grp package is used to implement a sudo-like functionality.  If you run an SHTK script as root, it allows you to switch between users.  Unfortunately that package is not available on Windows.

**Comment by jroose** [comment]
Closing because old thread with answered question.
